module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    FUEL_ADD_NEW: "FUEL_ADD_NEW",
    CAR_ADD_NEW: "CAR_ADD_NEW",
    VIDANGE_ADD_NEW: "VIDANGE_ADD_NEW",
    ADD_NEW: "ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    VIDANGE_DELETE: "VIDANGE_DELETE",
    FUEL_DELETE: "FUEL_DELETE",
  },
});
